export default {
  ta: {
    all: "அனைத்தும்",
    allLanguages: "அனைத்து மொழிகள்",
    about: "பற்றி",
    backToTop: "மேலே செல்ல",
    category: "வகை",
    copy: "நகலெடு",
    cook: "சமைப்பு",
    difficulty: "சிரமம்",
    featured: "சிறப்பு",
    footer: "அடிப்பகுதி",
    home: "முகப்பு",
    ingredients: "பொருட்கள்",
    language: "மொழி",
    latest: "புதியவை",
    light: "வெளிச்சம்",
    dark: "இருள்",
    media: "ஊடகம்",
    menu: "பட்டி",
    mute: "ஒலி அணை",
    next: "அடுத்தது",
    noMatches: "பொருத்தம் இல்லை",
    noRecipesFound: "சமையல் குறிப்புகள் இல்லை.",
    nonVeg: "Non-Veg",
    nutrition: "ஊட்டச்சத்து",
    page: "பக்கம்",
    pageOf: "இல்",
    pip: "PiP",
    prep: "தயாரிப்பு",
    previous: "முந்தையது",
    print: "அச்சிடு",
    random: "அதிரடி",
    randomRecipe: "அதிரடி சமையல் குறிப்பு",
    read: "வாசிப்பு",
    readMin: "நிமிடம்",
    recipes: "சமையல்கள்",
    recipeNavigation: "சமையல் வழிசெலுத்தல்",
    recipeTools: "சமையல் கருவிகள்",
    relatedRecipes: "தொடர்புடைய சமையல்கள்",
    scale: "அளவு மாற்று",
    search: "தேடல்",
    searchIngredients: "பொருட்களை தேடுக",
    searchIndexUnavailable: "தேடல் பட்டியல் கிடைக்கவில்லை",
    searchPlaceholder: "சமையல் தேடுக - / அழுத்தவும்",
    searchRecipes: "சமையல் தேடுக",
    servings: "பரிமாறல்",
    skipToContent: "உள்ளடக்கத்துக்கு செல்ல",
    system: "கணினி",
    tags: "குறிச்சொற்கள்",
    theme: "தீம்",
    total: "மொத்தம்",
    veg: "Veg",
    watchOnInstagram: "Instagram-ல் பார்க்க",
    watchOnYouTube: "YouTube-ல் பார்க்க"
  },
  en: {
    all: "All",
    allLanguages: "All languages",
    about: "About",
    backToTop: "Back to top",
    category: "Category",
    copy: "Copy",
    cook: "Cook",
    difficulty: "Difficulty",
    footer: "Footer",
    featured: "Featured",
    home: "Home",
    ingredients: "Ingredients",
    language: "Language",
    latest: "Latest",
    light: "Light",
    dark: "Dark",
    media: "Media",
    menu: "Menu",
    mute: "Mute",
    next: "Next",
    noMatches: "No matches",
    noRecipesFound: "No recipes found.",
    nonVeg: "Non-Veg",
    nutrition: "Nutrition",
    page: "Page",
    pageOf: "of",
    pip: "PiP",
    prep: "Prep",
    previous: "Previous",
    print: "Print",
    random: "Random",
    randomRecipe: "Random recipe",
    read: "Read",
    readMin: "min",
    recipes: "Recipes",
    recipeNavigation: "Recipe navigation",
    recipeTools: "Recipe tools",
    relatedRecipes: "Related recipes",
    scale: "Scale",
    search: "Search",
    searchIngredients: "Search ingredients",
    searchIndexUnavailable: "Search index unavailable",
    searchPlaceholder: "Search recipes - press /",
    searchRecipes: "Search recipes",
    servings: "Servings",
    skipToContent: "Skip to content",
    system: "System",
    tags: "Tags",
    theme: "Theme",
    total: "Total",
    veg: "Veg",
    watchOnInstagram: "Open on Instagram",
    watchOnYouTube: "Watch on YouTube"
  }
};
